### PR TITLE
Implemented denormalize

### LINKED ISSUE #10: Implementation of denormalization?
Thanks for the lib!

I think, it would be convenient to have a denormalization function in pair with normalization, like in original `normalizr`. What do you think about it?

### PR DESCRIPTION
**Pull request by zeorin**
Fixes #10.

### CODE REVIEW

**Comment by zeorin** [comment]
@stevenpetryk Would you mind having a look at this PR, please? :smiley:

**Comment by sergii-zhuravel** [comment]
@stevenpetryk Is this lib still under your support and maintenance?

**Comment by zeorin** [comment]
@stevenpetryk Another ping. Please have a look at this PR.

**Comment by stevenpetryk** [comment]
Thanks so much for this @zeorin. I am going to close this PR for now while the issue is discussed further. For those of you who need this particular implementation of denormalize, I encourage you to use @zeorin's branch:

```
npm install --save git@github.com:zeorin/jsonapi-normalizer.git#feature/denormalize
```

**Comment by zeorin** [comment]
Hi all, because packages on npm are often built before publishing, please use the following branch instead:

```
npm install --save git@github.com:zeorin/jsonapi-normalizer.git#denormalize-built
```

**Pull request closed without merging**
